apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-server-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-server-sa
    namespace: default
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io